package com.cxx;
import com.cxx.bean.Sale;
import java.math.*;
import java.util.*;

rule "Sat-and-Sun-90%"//周六周日九折
    no-loop true
    lock-on-active true
    salience 3
    when
        $s:Sale( getDayOfWeek() == 1 || getDayOfWeek() == 7);
    then
        $s.setDiscount(new BigDecimal(0.9));
//        System.out.println("九折："+$s.getSaleCode());
        update($s);
     end

rule "100-80%"//满一百打八折
    no-loop true
    lock-on-active true
    salience 2
    when
        $s:Sale( getTotal() >= 100);
    then
        $s.setDiscount(new BigDecimal(0.8));
//        System.out.println("八折："+$s.getSaleCode());
        update($s);
     end


rule "200-70%"//满两百打七折
    no-loop true
    lock-on-active true
    salience 1
    when
            $s:Sale( getTotal() >= 200);
    then
            $s.setDiscount(new BigDecimal(0.7));
//            System.out.println("七折："+$s.getSaleCode());
            update($s);
    end
